# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: rpc.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\trpc.proto\"\'\n\x12stockLookupMessage\x12\x11\n\tstockName\x18\x01 \x02(\t\"K\n\x1astockLookupResponseMessage\x12\x16\n\x0elookupResponse\x18\x01 \x02(\x02\x12\x15\n\rtradingVolume\x18\x02 \x01(\x05\"F\n\x18stockTradeRequestMessage\x12\x11\n\tstockName\x18\x01 \x02(\t\x12\t\n\x01N\x18\x02 \x02(\x05\x12\x0c\n\x04type\x18\x03 \x02(\t\"0\n\x19stockTradeResponseMessage\x12\x13\n\x0btradeResult\x18\x01 \x02(\x05\"=\n\x19stockUpdateRequestMessage\x12\x11\n\tstockName\x18\x01 \x02(\t\x12\r\n\x05price\x18\x02 \x02(\x02\"2\n\x1astockUpdateResponseMessage\x12\x14\n\x0cupdateResult\x18\x01 \x02(\x05\x32\xd2\x01\n\x0bStockBazaar\x12<\n\x06Lookup\x12\x13.stockLookupMessage\x1a\x1b.stockLookupResponseMessage\"\x00\x12@\n\x05Trade\x12\x19.stockTradeRequestMessage\x1a\x1a.stockTradeResponseMessage\"\x00\x12\x43\n\x06Update\x12\x1a.stockUpdateRequestMessage\x1a\x1b.stockUpdateResponseMessage\"\x00')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'rpc_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _STOCKLOOKUPMESSAGE._serialized_start=13
  _STOCKLOOKUPMESSAGE._serialized_end=52
  _STOCKLOOKUPRESPONSEMESSAGE._serialized_start=54
  _STOCKLOOKUPRESPONSEMESSAGE._serialized_end=129
  _STOCKTRADEREQUESTMESSAGE._serialized_start=131
  _STOCKTRADEREQUESTMESSAGE._serialized_end=201
  _STOCKTRADERESPONSEMESSAGE._serialized_start=203
  _STOCKTRADERESPONSEMESSAGE._serialized_end=251
  _STOCKUPDATEREQUESTMESSAGE._serialized_start=253
  _STOCKUPDATEREQUESTMESSAGE._serialized_end=314
  _STOCKUPDATERESPONSEMESSAGE._serialized_start=316
  _STOCKUPDATERESPONSEMESSAGE._serialized_end=366
  _STOCKBAZAAR._serialized_start=369
  _STOCKBAZAAR._serialized_end=579
# @@protoc_insertion_point(module_scope)
